apiVersion: v1
kind: ConfigMap
metadata:
  name: oar3conf
  namespace: oar
data:
  PG_HOST: "db-server"
  PG_PORT: "5432"
  PG_OAR_BASE_NAME: "oar"
  PG_OAR_BASE_USERNAME: "oar"
  PG_OAR_BASE_USERPASS: "azerty"
  PG_OAR_BASE_USERNAME_RO: "oar_ro"
  PG_OAR_BASE_USERPASS_RO: "azerty"
  OAR_SERVER_HOSTNAME: "hpc-scheduler"
  KUBERNETES_NAMESPACE: "oar"
  ALMIGHTY_CONTAINER: "oar-server"
  API_HOST: "api-server"
  API_PORT: "6668"
  HOME_PVC: "pvc-nfs-home"
  HOME_MOUNT_NAME: "home"
  HOME_MOUNT_PATH: "/home"
  NET_SERVICE: "nodes"
  KUBERNETES_DOMAIN: "svc.cluster.local"
  WALL_TIME_IDLE_POD: "30"
---
apiVersion: v1
kind: Service
metadata:
  name: nodes
  namespace: oar
spec:
  selector:
    net: headless
  clusterIP: None
---
apiVersion: v1
kind: Pod
metadata:
  name: hpc-scheduler
  namespace: oar
  labels:
    name: hpc-scheduler
    net: headless
    role: scheduler
  annotations:
    default/nodes: "3"
    default/cpuspernode: "2"
    default/image: "nyk0/chsc-oar3"
    default/hostnamebase: "hpc-node"
spec:
  hostname: hpc-scheduler
  subdomain: nodes
  initContainers:
  - name: check-postgres
    image: postgres
    command: ['sh', '-c', 
      'until pg_isready -h db-server -p 5432; 
      do echo waiting for database; sleep 2; done;']
  containers:
  - image: nyk0/chsc-oar3
    name: oar-server
    workingDir: /
    envFrom:
    - configMapRef:
        name: oar3conf
    command: ["/bin/bash"]
    args: ["/start-almighty.sh"]
    volumeMounts:
        - mountPath: /home
          name: home
  volumes:
    - name: home
      persistentVolumeClaim:
        claimName: pvc-nfs-home
  dnsConfig:
    searches:
      - nodes.oar.svc.cluster.local
---
apiVersion: v1
kind: Pod
metadata:
  name: api-server
  namespace: oar
  labels:
    name: api-server
    net: headless
spec:
  hostname: api-server
  subdomain: nodes
  containers:
  - image: nyk0/chsc-oar3
    name: api-server
    workingDir: /
    envFrom:
    - configMapRef:
        name: oar3conf
    command: ["/bin/bash"]
    args: ["/start-api.sh"]
  dnsConfig:
    searches:
      - nodes.oar.svc.cluster.local
---
apiVersion: v1
kind: Pod
metadata:
  name: db-server
  namespace: oar
  labels:
    name: db-server
    net: headless
spec:
  hostname: db-server
  subdomain: nodes
  containers:
  - image: postgres
    name: postgres
    env:
    - name: POSTGRES_PASSWORD
      value: "azerty"
    - name: POSTGRES_USER
      value: "root"
  dnsConfig:
    searches:
      - nodes.oar.svc.cluster.local
---
apiVersion: v1
kind: Pod
metadata:
  name: controller
  namespace: oar
  labels:
    name: controller
    net: headless
spec:
  hostname: controller
  subdomain: nodes
  containers:
  - image: nyk0/chsc-oar3
    name: controller
    workingDir: /
    envFrom:
    - configMapRef:
        name: oar3conf
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
  dnsConfig:
    searches:
      - nodes.oar.svc.cluster.local
