---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list-oar
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list","create","delete","get"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list-oar
subjects:
- kind: ServiceAccount
  name: default
  namespace: oar
roleRef:
  kind: ClusterRole
  name: pods-list-oar
  apiGroup: rbac.authorization.k8s.io
